if(NOT DEFINED CONTRACT_FILE OR NOT EXISTS "${CONTRACT_FILE}")
    message(FATAL_ERROR "Native FUI capability contract is missing: ${CONTRACT_FILE}")
endif()
if(NOT DEFINED STUB_FILE OR NOT EXISTS "${STUB_FILE}")
    message(FATAL_ERROR "Native FUI stub source is missing: ${STUB_FILE}")
endif()
if(NOT DEFINED REAL_FILE OR NOT EXISTS "${REAL_FILE}")
    message(FATAL_ERROR "Native FUI real bridge source is missing: ${REAL_FILE}")
endif()
if(NOT DEFINED FFI_FILE OR NOT EXISTS "${FFI_FILE}")
    message(FATAL_ERROR "Generated FUI-RS FFI source is missing: ${FFI_FILE}")
endif()

file(STRINGS "${CONTRACT_FILE}" contract_lines)
file(READ "${STUB_FILE}" stub_source)
file(READ "${REAL_FILE}" real_source)
file(READ "${FFI_FILE}" ffi_source)
string(REGEX MATCHALL "fui_[A-Za-z0-9_]+[ \t\r\n]*\\(" stub_matches "${stub_source}")
string(REGEX MATCHALL "fui_[A-Za-z0-9_]+[ \t\r\n]*\\(" real_matches "${real_source}")

set(stub_symbols)
foreach(match IN LISTS stub_matches)
    string(REGEX REPLACE "[ \t\r\n]*\\($" "" symbol "${match}")
    list(APPEND stub_symbols "${symbol}")
endforeach()
list(REMOVE_DUPLICATES stub_symbols)

set(real_symbols)
foreach(match IN LISTS real_matches)
    string(REGEX REPLACE "[ \t\r\n]*\\($" "" symbol "${match}")
    list(APPEND real_symbols "${symbol}")
endforeach()
list(REMOVE_DUPLICATES real_symbols)

set(contract_symbols)
foreach(line IN LISTS contract_lines)
    if(line STREQUAL "" OR line MATCHES "^#")
        continue()
    endif()

    string(REPLACE "|" ";" fields "${line}")
    list(LENGTH fields field_count)
    if(NOT field_count EQUAL 6)
        message(FATAL_ERROR "Malformed native FUI capability row (${field_count} fields): ${line}")
    endif()

    list(GET fields 0 symbol)
    list(GET fields 1 classification)
    list(GET fields 2 state)
    list(GET fields 3 owner)
    list(GET fields 4 reference)
    list(GET fields 5 invalid_input)
    list(APPEND contract_symbols "${symbol}")
    list(FIND contract_symbols "${symbol}" first_contract_index)
    list(LENGTH contract_symbols contract_length)
    math(EXPR expected_last_index "${contract_length} - 1")
    if(NOT first_contract_index EQUAL expected_last_index)
        message(FATAL_ERROR "Duplicate native FUI capability contract row: ${symbol}")
    endif()

    if(NOT symbol MATCHES "^fui_[A-Za-z0-9_]+$")
        message(FATAL_ERROR "Invalid native FUI capability symbol: ${symbol}")
    endif()
    if(NOT classification MATCHES "^(required|browser-only|native-fallback|deliberately-unsupported)$")
        message(FATAL_ERROR "Invalid classification for ${symbol}: ${classification}")
    endif()
    if(owner STREQUAL "" OR reference STREQUAL "" OR invalid_input STREQUAL "")
        message(FATAL_ERROR "Incomplete capability contract for ${symbol}")
    endif()

    list(FIND stub_symbols "${symbol}" stub_index)
    if(classification STREQUAL "required")
        if(state STREQUAL "implemented")
            if(NOT stub_index EQUAL -1)
                message(FATAL_ERROR "Required native FUI capability returned to the stub source: ${symbol}")
            endif()
            list(FIND real_symbols "${symbol}" real_index)
            if(real_index EQUAL -1)
                message(FATAL_ERROR "Required native FUI capability has no real bridge definition: ${symbol}")
            endif()
        elseif(state MATCHES "^gap-phase-[0-9]+$")
            if(stub_index EQUAL -1)
                message(FATAL_ERROR "Contract marks ${symbol} as a gap but the stub is absent; mark it implemented")
            endif()
        else()
            message(FATAL_ERROR "Invalid required capability state for ${symbol}: ${state}")
        endif()
    else()
        if(NOT state STREQUAL "intentional-stub")
            message(FATAL_ERROR "Intentional platform difference has invalid state for ${symbol}: ${state}")
        endif()
        if(stub_index EQUAL -1)
            message(FATAL_ERROR "Intentional stub is missing or its contract is stale: ${symbol}")
        endif()
    endif()
endforeach()

# Browser service families are public FUI-RS imports. Every generated member
# must be classified so dead-code elimination cannot conceal a missing native
# definition until an application first uses it.
string(REGEX MATCHALL "pub fn fui_(fetch|worker|file)_[A-Za-z0-9_]+" public_family_matches "${ffi_source}")
foreach(match IN LISTS public_family_matches)
    string(REGEX REPLACE "^pub fn " "" symbol "${match}")
    list(FIND contract_symbols "${symbol}" contract_index)
    if(contract_index EQUAL -1)
        message(FATAL_ERROR "Unclassified public native FUI service import: ${symbol}")
    endif()
endforeach()

# Tier 1, Tier 2, and the headless host must remain independent of the FUI
# application ABI. Platform hosts are the first layer allowed to link it.
if(DEFINED SOURCE_ROOT)
    file(GLOB_RECURSE boundary_sources LIST_DIRECTORIES false
        "${SOURCE_ROOT}/v2/core/*.cpp" "${SOURCE_ROOT}/v2/core/*.h"
        "${SOURCE_ROOT}/v2/ui/*.cpp" "${SOURCE_ROOT}/v2/ui/*.h"
        "${SOURCE_ROOT}/v2/native/headless/*.cpp" "${SOURCE_ROOT}/v2/native/headless/*.h")
    foreach(source IN LISTS boundary_sources)
        file(READ "${source}" boundary_source)
        if(boundary_source MATCHES "fui_[A-Za-z0-9_]+" OR boundary_source MATCHES "NativeFui")
            message(FATAL_ERROR "FUI dependency leaked below the native platform-host boundary: ${source}")
        endif()
    endforeach()
endif()

list(REMOVE_DUPLICATES contract_symbols)
foreach(symbol IN LISTS stub_symbols)
    list(FIND contract_symbols "${symbol}" contract_index)
    if(contract_index EQUAL -1)
        message(FATAL_ERROR "Unclassified native FUI stub: ${symbol}")
    endif()
endforeach()

list(LENGTH contract_symbols contract_count)
list(LENGTH stub_symbols stub_count)
message(STATUS "Native FUI capability contract verified: ${contract_count} capabilities, ${stub_count} current stubs")
